/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.3/userguide/building_swift_projects.html in the Gradle documentation.
 */


plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}




var buildFiles = fileTree(rootDir) {
    val excludes = gradle.startParameter.projectProperties["excludeProjects"]?.split(",")
    include("**/*.gradle.kts")
    exclude("build", "**/gradle", "settings.gradle.kts", "buildSrc", "/build.gradle.kts", ".", "out")
    if (!excludes.isNullOrEmpty()) {
        exclude(excludes)
    }
}

rootProject.name = "starter"

buildFiles.forEach {
    val isDefaultName = it.name == "build.gradle" || it.name == "build.gradle.kts"
    if (isDefaultName) {
        val buildFilePath = it.parentFile.absolutePath
        val projectName = buildFilePath.replace(rootDir.absolutePath, "").replace(File.separator, "")
        val projectPath = ":$projectName"
        include(projectPath)
    }else {
        val projectName = it.name.replace(".gradle.kts","").replace(".gradle","")
        val projectPath = ":$projectName"
        include(projectPath)
        val project = findProject(projectPath)
        if (project!=null){
            project.name = projectName
            project.projectDir = it.parentFile
            project.buildFileName = it.name
        }
    }
}
