[versions]
spring = "5.3.27"
springBoot = "3.4.0"
kotlin = "1.9.0"
springDependencyManagement = "1.1.7"
gradleChangelogPlugin = "2.2.1"

lombok = "1.18.34"
mapstruct = "1.6.3"

[libraries]
spring-boot-plugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "springBoot" }

lombok = {group = "org.projectlombok", name = "lombok", version.ref = "lombok"}
mapstruct = {group="org.mapstruct", name="mapstruct-processor", version.ref="mapstruct"}

[bundles]


[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
